import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

/*
 * Stamp the build into src/app/version.ts, shown at the foot of the overflow
 * menu. It exists because of an afternoon spent debugging a "bug" that was a
 * phone showing a cached build from hours earlier: with the stamp on screen,
 * "which version are you actually looking at" has an answer.
 */
const hash = execSync('git rev-parse --short HEAD').toString().trim();
const now = new Date();
const pad = n => String(n).padStart(2, '0');
const stamp = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${pad(now.getHours())}:${pad(now.getMinutes())}`;

writeFileSync(
  'src/app/version.ts',
  `// Generated by scripts/stamp-version.mjs — do not edit, not tracked.\nexport const APP_VERSION = '${hash} · ${stamp}';\n`,
);
console.log(`version ${hash} · ${stamp}`);
